name: yoke_lambdablade_<YYMMDD>
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.6.0=h6a678d5_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - bottleneck=1.3.7=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py312h6a678d5_8
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - coverage=7.2.2=py312h5eee18b_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.0=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.4.0=0
  - cuda-version=12.6=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - docutils=0.18.1=py312h06a4308_3
  - einops=0.8.0=pyhd8ed1ab_0
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - flit=3.9.0=py312h06a4308_1
  - flit-core=3.9.0=py312hee27c6d_1
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h5py=3.11.0=py312h34c39bb_0
  - hdf5=1.12.1=h2b7332f_3
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - imagecodecs=2023.1.23=py312h81b8100_1
  - imageio=2.33.1=py312h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py312h06a4308_0
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py312h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libavif=0.11.1=h5eee18b_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.4.2.65=0
  - libcufft=11.2.0.44=0
  - libcufile=1.11.1.6=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.7.77=0
  - libcurl=8.9.1=h251f7ec_0
  - libcusolver=11.6.0.99=0
  - libcusparse=12.3.0.142=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.2=0
  - libnvfatbin=12.6.77=0
  - libnvjitlink=12.4.99=0
  - libnvjpeg=12.3.1.89=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - libzopfli=1.0.3=he6710b0_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.9.2=py312h06a4308_0
  - matplotlib-base=3.9.2=py312h66fe004_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.10=py312h5eee18b_0
  - mkl_random=1.2.7=py312h526ad5a_0
  - mpmath=1.3.0=py312h06a4308_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py312h06a4308_0
  - numexpr=2.8.7=py312hf827012_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=py312h06a4308_0
  - pandas=2.2.2=py312h526ad5a_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.4.0=py312h5eee18b_0
  - pip=24.2=py312h06a4308_0
  - pluggy=1.0.0=py312h06a4308_1
  - ply=3.11=py312h06a4308_1
  - pybind11-abi=5=hd3eb1b0_0
  - pyparsing=3.1.2=py312h06a4308_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - pytest=7.4.4=py312h06a4308_0
  - pytest-cov=4.1.0=py312h06a4308_1
  - python=3.12.5=h5148396_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.4.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py312h06a4308_0
  - ruff=0.3.5=py312hab49468_0
  - scikit-image=0.24.0=py312h526ad5a_0
  - scikit-learn=1.5.1=py312h526ad5a_0
  - scipy=1.13.1=py312hc5e2394_0
  - setuptools=75.1.0=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tifffile=2023.4.12=py312h06a4308_0
  - tk=8.6.14=h39e8969_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli-w=1.0.0=pyhd3eb1b0_0
  - torchaudio=2.4.1=py312_cu124
  - torchtriton=3.0.0=py312
  - torchvision=0.19.1=py312_cu124
  - tornado=6.4.1=py312h5eee18b_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.2.3=py312h06a4308_0
  - wheel=0.44.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zfp=1.0.0=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
prefix: yoke_lambdablade_<YYMMDD>
